<?php

namespace App\Lib\Classes;

use App\Core\Lava\Lava;
use App\Core\Smarty\Smarty;

class PublicParser extends Smarty
{
	private $inline;
	public function __construct(Lava $app, $options = [])
	{
		parent::__construct();

		$this->setTemplateDir([
			BASE_PATH . 'templates'
		]);
		$this->setCompileDir(BASE_PATH . 'public/tpl_compiled/public');

		$this->setCaching(false);

		$this->force_compile = true;

		$this->registerPlugin('modifier', 'base64_encode', 'base64_encode');
		$this->registerPlugin('modifier', 'slash', 'addslashes');

		$this->assign(compact('app'));

		$this->inline = (array_key_exists('inline', $options) ? $options['inline'] : $app->isAjax());

		if (!$this->inline) {
			//
		}
	}

	public function display($template = null, $cache_id = null, $compile_id = null, $parent = null)
	{
		parent::display($template, $cache_id, $compile_id, $parent); // TODO: Change the autogenerated stub
	}
}